version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
  nginx:
    image: nginx:alpine
    ports:
      - 80:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app